name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master
        with:
          host: 100.26.252.2
          username: ubuntu
          private-key: 
           
          script: |
            cd /var/www/myapp
            git pull origin main
            sudo systemctl reload nginx

      - name: Deploy to Server 2
        uses: appleboy/ssh-action@master
        with:
          host: 54.237.27.95
          username: ubuntu
          private-key: 
          script: |
            cd /var/www/myapp
            git pull origin main
            sudo systemctl reload nginx
